### ISSUE TITLE
onReceivedError and onReceivedHttpError does not work on API level < 23

### ISSUE THREAD

**Issue by strooonger** [uber/rides-android-sdk#105]
Repro steps, stacktrace, screenshots:
1. Launch "request-button-sample"
2. Press "Get a ride" button in "Ride Request Widget" (the one in the bottom)
3. Immediately change to "Airplane mode"

Expected Behavior:
![image](https://user-images.githubusercontent.com/34035150/34371482-a8975aec-eb08-11e7-835e-5bed750512b6.png)

Actual Behavior:
![image](https://user-images.githubusercontent.com/34035150/34371844-7232cc86-eb0b-11e7-9dc9-a2081734afae.png)

Root cause:
"onReceivedError" does not execute when API level < 23, making the code snippet you have written in "onReceivedError" will not execute. As a result, the "WebView" object will not finish and the error message will not show.

Also "onReceivedHttpError" is introduced in API level 23, not compatible for the former version of Android devices, it can also cause this happen

https://github.com/uber/rides-android-sdk/blob/4d77c38aa9cfe0c925a0ede2894992fd89710e5e/core-android/src/main/java/com/uber/sdk/android/core/auth/LoginActivity.java#L221-L229

https://github.com/uber/rides-android-sdk/blob/85d9936b8b74713897e858d9cb03a5159cf1e5eb/rides-android/src/main/java/com/uber/sdk/android/rides/RideRequestView.java#L264-L274

Testing Device:
Nexus 5X API 23 and 22

**Comment by tyvsmith** [comment]
Thanks for the report! Since we're in the process of moving to an implementation that uses redirect URIs registered in the manifest and Chrometabs in favor of webviews https://github.com/uber/rides-android-sdk/issues/22, this error handling on older devices is not prioritized as highly. If you want it quicker, please submit a PR using the following method and we'll merge that.  Otherwise, this correction will come at a later date.

```
void onReceivedError (WebView view, 
                int errorCode, 
                String description, 
                String failingUrl) {

}
```
