### ISSUE TITLE
Use ChromeTabs for OAuth2 web forms

### ISSUE THREAD

**Issue by arogal** [uber/rides-android-sdk#22]

**Comment by hzsweers** [comment]
These tend to be finicky since you can't control the custom tab after it's been created. You can foreground your new activity to respond to the callback, but the user will still be able to press back and go back to the tab again. Chrome team was looking into supporting this use case better awhile back but not sure what happened.

**Comment by arogal** [comment]
Thanks. We've reached out to Google (both the chrome and identity teams) to
see if there is a proper way to do this.

**Comment by giowild** [comment]
Hi, are there any news about this topic?

**Comment by tyvsmith** [comment]
This is implemented from #108
