### ISSUE TITLE
SessionConfiguration.Environment.SANDBOX explanation

### ISSUE THREAD

**Issue by lawloretienne** [uber/rides-android-sdk#50]
If I called `setEnvironment(SessionConfiguration.Environment.SANDBOX)`, what exactly does that mean?  Does it mean that an actual Uber ride will NOT be requested?

I have called 

`uberButton.setRequestBehavior(new RideRequestActivityBehavior(getActivity(), REQUEST_UBER_REQUEST_CODE));`

If I request an Uber in Sandbox mode, will it come back to the `onActivityResult()` callback method with `resultCode == Activity.RESULT_OK`?

Maybe you could spell this out in your README, unless you explain it somewhere else.

**Comment by lawloretienne** [comment]
![screenshot_20160901-120549](https://cloud.githubusercontent.com/assets/311187/18181155/b8e5e440-703e-11e6-91fb-4c9b7ec9b22d.png)

It never gets past this screen.

**Comment by itstexter** [comment]
Hey @lawloretienne!

Thanks for your issue! You've called out something we totally missed in our Android documentation. In the [Rides Java SDK](https://github.com/uber/rides-java-sdk)'s README we call out sandbox behavior, but we totally don't in this repo's README.

You can read about sandbox behavior in our [documentation](https://developer.uber.com/docs/rides/sandbox). As you've guessed, a real Uber ride will not be requested when in the sandbox environment. You can manipulate the state of your sandbox ride as described in the documentation on the Uber developers site or Rides Java SDK README linked above.

The Ride Request Widget won't return any activity results back to you, the REQUEST_CODE you're sending in is used for login, which I'm realizing now has an overlap in meaning because of requesting a ride vs starting an activity with an Android request code.

I'll update the Android README to include the Sandbox info and will change the name of requestCode to something like requestCodeForLogin. Thanks so much for calling out these inconsistencies!

**Comment by lawloretienne** [comment]
I appreciate your quick response and i'm glad i could bring this to your attention so it will help other developers.  

1) So the Ride Request Widget will not return any results back to you so there is no need to set up an onActivityResult() method, right?

2) Also while in Sandbox mode can you ever get past that Requesting ride screen or does it intentionally just hang there?

**Comment by itstexter** [comment]
1) Basically. Functionality speaking you don't need to set up an `onActivityResult()`. The `Ride Request Widget` should show error messages and handling to the user on its own. However any errors that occur in the widget will be communicated back with a result code of `RESULT_CANCELED` and the specific error code captured as an extra (either as `"authentication_error"` or as `ride_request_error`) so if you wanted to know when and why the widget failed, you could use `onActivityResult()` in that manner.

2) In `Sandbox` mode you can get past the Requesting screen. You'll need the `request` scope to do so, but with it you can create a `RidesService` and use `getCurrentRide` to get your Ride ID. With that you can hit `updateSandboxRide` with some `SandboxRideRequestParameters`. This should cause the widget to change state as you update the sandbox ride.

**Comment by lawloretienne** [comment]
I have these scopes set up :
`.setScopes(Arrays.asList(Scope.RIDE_WIDGETS, Scope.REQUEST))`

I'm not sure where i should be creating a `RidesService`.  I have set up the uber button as follows :

```
private void setUpUberButton(Venue venue){
        Location location = venue.getLocation();
        if(location != null){
            float latitude = location.getLatitude();
            float longitude = location.getLongitude();
            String venueName = venue.getName();
            String address = location.getAddress();

            uberButton.setRequestBehavior(new RideRequestActivityBehavior(getActivity(), REQUEST_UBER_REQUEST_CODE));

            RideParameters rideParams = new RideParameters.Builder()
                    .setDropoffLocation((double)latitude, (double)longitude, venueName, address)
                    .build();
            uberButton.setRideParameters(rideParams);
      }
}
```

**Comment by itstexter** [comment]
Yup! Your setup of the button looks good to me so far, in a production app, you're probably done!

Because you want to make changes to the ride in sandbox, you now need to make a `RidesService`. You'll need to authenticate a user and get an access token in order to do this. If you want to do it all client side, I'd recommend using the `LoginButton` to get an access token for your user. Take a look at how the [LoginSampleActivity](https://github.com/uber/rides-android-sdk/blob/master/samples/login-sample/src/main/java/com/uber/sdk/android/samples/LoginSampleActivity.java) is using the `LoginButton` and `LoginManager` to authenticate the user. Once you've authenticated the user, you can create a `RidesService` with `Session session = loginManager.getSession();` and `RidesService service = UberRidesApi.with(session).createService();`. You can then use that service to make changes to the sandbox, though I'd recommend doing that off the main thread so you can also open the Ride Request Widget.

**Comment by lawloretienne** [comment]
By making changes to the ride in `Sandbox`, what exactly does that mean?  Are you referring to requesting UberX as opposed to UberXL like those options at the bottom of the `Ride Request Widget`?

Maybe I should just switch to Production if there is no further integration required.  I just wanted to see the flow complete in `Sandbox` mode, but i guess its not designed for that.

**Comment by itstexter** [comment]
It's not super well designed for that, no. Go ahead and kick it up in production to see what it will look like, no rides will be requested automatically until you personally press a "request a ride" button.

Changes to sandbox basically allow you to act like Uber's servers, you can have a "car" be assigned to your user, drive to pick them up, and then drop them off at their location. You can also control cars availability and surge pricing. Things like choosing Uber X as opposed to XL are done in the widget by the user.

I'd recommend booting up the widget in a production environment and taking a look at the [documentation](https://developer.uber.com/docs/rides/sandbox) on the sandbox.

**Comment by lawloretienne** [comment]
Thanks for all the info.  I appreciate it.

**Comment by itstexter** [comment]
Thanks for upping the bar on the quality of our SDK! I'll be integrating all of this conversation into our README over the next week, I really appreciate the outside insight you've provided.
